title: Theo Kanning
name: theokanning.com
description: Science is Awesome
baseurl: ""
url: "https://theokanning.github.io"

markdown: kramdown
remote_theme: rosario/kasper
paginate: 10
plugins:
  - jekyll-paginate

exclude:
  - run_local.sh
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
